Update quant ci examples
siliconflow/onediff pull request #792
Opened 2024-04-08 11:44 UTC by lijunliangTG

在 OneDiff CI 中，加入测试量化效果和原图差异的测试

相关要求如下
https://github.com/siliconflow/sd-team/issues/345

2024-04-08 15:55 UTC, lijunliangTG commented
![image](https://github.com/siliconflow/onediff/assets/117806079/1b7ce7b3-fcf8-4618-9ae6-d999f94c395e)
尝试通过量化后生成的图片直接放到share_nfs中但是失败，原因是权限问题，所以还是写在源路径下对比。

2024-04-09 06:26 UTC, doombeaker requested changes

2024-04-09 06:26 UTC, doombeaker commented on .github/workflows/examples.yml
> +          SILICON_ONEDIFF_LICENSE_KEY: ${{ secrets.SILICON_ONEDIFF_LICENSE_KEY }}
这一页行好像也是不必要的修改引入的

2024-04-09 06:26 UTC, doombeaker commented on tests/diffusers-docker-compose.yml
> -      - ${SDXL_BASE}:/app/ComfyUI/models/checkpoints/sd_xl_base_1.0.safetensors:ro
这两行删除好像是不必要的

2024-04-09 06:26 UTC, doombeaker commented on tests/ssim_compare.py
> +    validate()
文件末尾需要多一个空行

2024-04-09 06:26 UTC, doombeaker commented on tests/ssim_compare.py
> +import matplotlib.pyplot as plt
这个包没用到，不需要导入。

2024-04-09 06:26 UTC, doombeaker commented on tests/ssim_compare.py
> +from skimage.metrics import structural_similarity as ssim
这个文件的文件名改一下，和这个目录下的其它文件一致。叫做 "test_量化质量" 一类的（名字自己起一下）

2024-04-09 06:26 UTC, doombeaker commented on .github/workflows/examples.yml
> +          docker exec -w /src/onediff ${{ env.CONTAINER_NAME }} python3 onediff_diffusers_extensions/examples/text_to_image_sd_enterprise.py  --model /src/test/quantized_model_pth --width 512 --heigh
每次 CI 临时量化一个模型耗时比较多（将近10分钟了）。改成直接使用 `/share_nfs` 下已有的量化模型，直接生成一张图片吧。

2024-04-09 06:26 UTC, doombeaker commented on tests/ssim_compare.py
> +    if ssim_index < 0.85:
引入输入输出是可以确定的，这个阈值不会变化，需要“紧贴”着实际值，比如我看了日志这里的 ssim 是 0.89xxx，那这个阈值就定 0.89。

2024-04-09 06:26 UTC, doombeaker commented on tests/ssim_compare.py
> +        sys.exit(1)  # A status code other than 0 indicates a failure
参考其它文件的方式，改成 `assertTrue` 即可：https://github.com/siliconflow/onediff/blob/quant_test/tests/test_quantize_custom_model.py#L109

2024-04-09 06:33 UTC, doombeaker commented
> 尝试通过量化后生成的图片直接放到share_nfs中但是失败，原因是权限问题，所以还是写在源路径下对比。


这样做是对的，不应该在 CI 中往 `/share_nfs` 里写东西，因为 `/share_nfs` 是以只读方式挂载的。
而且因为 `/share_nfs` 是一个实际挂在上的操作系统，写入的文件会持续积累。

就放在容器的其它路径，这样 CI 结束，容器释放，这部分占用的空间也释放了

2024-04-10 01:29 UTC, doombeaker commented on tests/test_quantitative_quality.py
> +        print("SSIM:", ssim_index)
把这个 print 放在 assertTrue 之前。

2024-04-10 01:30 UTC, doombeaker commented on tests/test_quantitative_quality.py
> +import sys
这个 `sys` 没用到

2024-04-10 01:31 UTC, doombeaker commented on tests/test_quantitative_quality.py
> +
末尾需要空行，这个警告检查下

2024-04-10 01:33 UTC, doombeaker requested changes
根据 comment 修改后就可以合并

2024-04-10 01:39 UTC, doombeaker commented on .github/workflows/examples.yml
> -          SILICON_ONEDIFF_LICENSE_KEY: ${{ secrets.SILICON_ONEDIFF_LICENSE_KEY }}
和这个 PR 无关的地方，不要去修改，即使功能一样的修改也不要有。

2024-04-10 01:39 UTC, doombeaker commented on tests/diffusers-docker-compose.yml
> -      - $PWD:/src/onediff
这个文件不应该变化

2024-04-10 02:16 UTC, doombeaker commented on tests/test_quantitative_quality.py
> +        print("SSIM:", ssim_index)
```suggestion
        print("SSIM: ", ssim_index)
```

2024-04-10 02:17 UTC, doombeaker commented on tests/test_quantitative_quality.py
> +        print("SSIM: ", ssim_index)
```suggestion
        print("SSIM:", ssim_index)
```

2024-04-10 02:17 UTC, doombeaker approved these changes

2024-04-10 05:30 UTC, merged