ComfyUI online quantitative usage documentation in wiki
siliconflow/onediff pull request #809
Opened 2024-04-12 02:57 UTC by fmk345

2024-04-12 03:20 UTC, ccssu commented on wiki.md
> +wget -O  ComfyUI/models/v1-5-pruned-emaonly.ckpt  https://hf-mirror.com/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.ckpt
```suggestion
wget -O models/v1-5-pruned-emaonly.ckpt  https://hf-mirror.com/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.ckpt
```
已经有 cd ComfyUI， 不需要 在多一层 ComfyUI 目录 其他地方也需要同步修改。

2024-04-12 03:22 UTC, ccssu commented on wiki.md
> +## Usage:
加个 使用前 请用 `$ python -m oneflow --doctor`  安装的 enterprise: True

2024-04-12 03:38 UTC, fmk345 commented on wiki.md
> +wget -O  ComfyUI/models/v1-5-pruned-emaonly.ckpt  https://hf-mirror.com/runwayml/stable-diffusion-v1-5/resolve/main/v1-5-pruned-emaonly.ckpt
已经修改
![image](https://github.com/siliconflow/onediff/assets/74238139/4c5ab79c-75ca-4269-b379-ebf956421a74)

2024-04-12 06:27 UTC, ccssu commented on wiki.md
> +3. Before use, please confirm with `$ python -m oneflow --doctor` to confirm the argument `enterprise: True`. If the argument `enterprise: False`, then uninstall oneflow through the following command
`pip uninstall oneflow -y  && pip uninstall onediff_quant -y `
Then follow the installation instructions for the Enterprise version to reinstall the OneDiff Enterprise version. You can find the relevant installation instructions through the following link: [OneDiff Enterprise Installation Instructions](https://github.com/siliconflow/onediff/blob/main/README_ENTERPRISE.md#install-onediff-enterprise)

2024-04-15 02:28 UTC, ccssu commented on wiki.md
> +## Online quantization for comfyui
整体上应该没问题，有两个小地方建议可以优化下：
1. wiki 换个名字比如：
    - onediff/onediff_comfy_nodes/workflows/`ComfyUI_Online_Quantization.md`
    - onediff/onediff_comfy_nodes/workflows/`efficient_online_quantization_for_comfyui.md`

2. 下图 ComfyUI with OneDiff Enterprise 的文档索引：
    - <img width="902" alt="image" src="https://github.com/siliconflow/onediff/assets/109639975/b8c4a780-2878-4660-8992-e12afcc56447">
   - 在画红框 子目录加个索引链接。

2024-04-15 07:45 UTC, ccssu approved these changes

2024-04-15 08:58 UTC, doombeaker requested changes

2024-04-15 08:58 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
> +## Online quantization for comfyui
标题的级别是不对的。文章标题应该是一级的

```
# Online quantization for comfyui
```

然后再是依次的二级、三级。这个文章里的标题级别，都需要检查和更新下。

2024-04-15 08:58 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
> +## Online quantization for comfyui
文章标题的大小写也需要规范。

```
 Online Quantization for ComfyUI
```

2024-04-15 08:58 UTC, doombeaker commented on README_ENTERPRISE.md
> +### Online quantization for comfyUI
标题大小写问题改一下。

另外这个 section，需要加入到文章开头的目录里，支持跳转。

2024-04-15 08:58 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
> +1. [OneDiff Installation Guide](https://github.com/siliconflow/onediff/blob/main/README_ENTERPRISE.md#install-onediff-enterprise)
```suggestion
1. [OneDiff Enterprise Installation Guide](https://github.com/siliconflow/onediff/blob/main/README_ENTERPRISE.md#install-onediff-enterprise)
```

应该是商业版安装的说明。要不很多人会以为社区版也可以

2024-04-15 08:58 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
> +3. Before use, please confirm with `$ python -m oneflow --doctor` to confirm the argument `enterprise: True`. If the argument `enterprise: False`, then run the following command`pip uninstall oneflow
```suggestion
3. Before use, please confirm with `python3 -m oneflow --doctor` to confirm the argument `enterprise: True`. If the argument `enterprise: False`, then run the following command`pip uninstall oneflow -y  && pip uninstall onediff_quant -y`, and then follow the installation instructions for the Enterprise version to reinstall the OneDiff Enterprise version. You can find the relevant installation instructions through the following link: [OneDiff Enterprise Installation Instructions](https://github.com/siliconflow/onediff/blob/main/README_ENTERPRISE.md#install-onediff-enterprise)
```

2024-04-15 08:58 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
> +3. Before use, please confirm with `$ python -m oneflow --doctor` to confirm the argument `enterprise: True`. If the argument `enterprise: False`, then run the following command`pip uninstall oneflow
`pip uninstall oneflow -y  && pip uninstall onediff_quant -y` 应该可以统一成一个命令：

```
pip uninstall oneflow onediff_quant -y
```

2024-04-15 08:58 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
> +3. Before use, please confirm with `$ python -m oneflow --doctor` to confirm the argument `enterprise: True`. If the argument `enterprise: False`, then run the following command`pip uninstall oneflow
其实这段最好直接给实例，就是说运行 doctor 命令后，应该得到类似如下的输出信息：

xxxx
xxxx

如果 enterprise 显示 `enterprise: False`，再应该如何做。

2024-04-15 08:58 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
> +
![image](https://github.com/siliconflow/onediff/assets/3351623/a565b3cc-a25a-404c-8b1b-923c98bbb524)

表格显示应该是有问题的，需要检查修改下（应该是用了中文符号 "|"）。

这类问题以后要自己预览自己检查掉。

2024-04-15 08:58 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
> +| quantized_linear_percentage           | [0, 100] | 100     | Example value representing 100% quantization for convolutional layers  |
```suggestion
| quantized_linear_percentage           | [0, 100] | 100     | Example value representing 100% quantization for convolutional layers.  |
```

要么统一由句号，要么统一没有。需要统一格式。

2024-04-15 08:58 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
> +1. Specify the directory for saving graphsusing export COMFYUI_ONEDIFF_SAVE_GRAPH_DIR="/path/to/save/graphs".
```suggestion
1. Specify the directory for saving graphs using `export COMFYUI_ONEDIFF_SAVE_GRAPH_DIR="/path/to/save/graphs"`.
```

2024-04-15 08:58 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
> +2. The log *.pt file is cached. Quantization result information can be found in `cache_dir`/quantization_stats.json.
```suggestion
2. The log `*.pt` file is cached. Quantization result information can be found in `cache_dir/quantization_stats.json`.
```

2024-04-15 08:58 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
> +## Usage:
我感觉可以把参数解释，放在 examples 那节之后。就是用户先跑起来（因为默认值也是不错的了），再来关心具体参数的设置。

2024-04-15 08:58 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
> +
作为 bash 命令，这个空行不必要，下同。

2024-04-15 08:58 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
> +- Python 3.10.13
这一段为什么要加。是要求用户必须用这些 commit 吗，如果不是，就不应该加，会增加不必要的纠结。

`python main.py --gpu-only` 如果是必须的，应该加在最开始运行的地方（先启动，再运行工作流）。

2024-04-15 08:58 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
> +| Baseline (non-optimized) | OneDiff(optimized) | OneDiff Quant(optimized) |
我觉得目录分级有点问题。比如上面的 SDXL 有  example，这里就没有了。

给这个文档的开始处，添加一个目录吧。添加的过程中，refine 下这个文档的目录分级。

2024-04-17 02:26 UTC, doombeaker commented
有冲突，需要先解决冲突

2024-04-17 06:21 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
> +| Baseline (non-optimized) | OneDiff(optimized) | OneDiff Quant(optimized) |
“给这个文档的开始处，添加一个目录吧。” 这个事情还没做。

2024-04-17 06:22 UTC, lijunliangTG commented on ComfyUI_Online_Quantization.md
1、补全pt文件附近的描述
2、增加对图表的描述

2024-04-17 06:26 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
> +## Usage:
是的，是指这里的参数。那你可以把这个参数说明单独做成一个章节。然后每个 examples 后引用这个章节，就不重复了。

2024-04-17 06:37 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
> +```
我认为不需要写 hf-mirror 的使用，如何使用 huggingface 镜像，不是 onediff 需要解决的问题。

就像给 pip install 安装命令，不需要额外说 CN 用户怎么配置镜像源

2024-04-17 06:37 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
这个文件的路径放在根目录我认为不合适。

2024-04-17 07:16 UTC, fmk345 commented on ComfyUI_Online_Quantization.md
> +```
我觉得应该写，如果是CN用户使用huggingface下载速度过慢经常下载过程中就断掉了

2024-04-17 07:51 UTC, fmk345 commented on ComfyUI_Online_Quantization.md
> +```
我觉得需要加，因为如果CN用户使用huggingface下载很慢而且中间易断，加入可以增强文档使用的方便性

2024-04-17 07:52 UTC, fmk345 commented on ComfyUI_Online_Quantization.md
> +# Online Quantization for Comfyui
done

2024-04-17 07:53 UTC, fmk345 commented on ComfyUI_Online_Quantization.md
放在了onediff/onediff_comfy_nodes/ComfyUI_Online_Quantization.md下

2024-04-17 08:18 UTC, fmk345 commented on ComfyUI_Online_Quantization.md
> +# Online Quantization for Comfyui
done

2024-04-17 08:38 UTC, fmk345 commented on ComfyUI_Online_Quantization.md
done

2024-04-17 08:39 UTC, fmk345 commented on ComfyUI_Online_Quantization.md
> +## Usage:
done

2024-04-17 09:03 UTC, doombeaker commented on ComfyUI_Online_Quantization.md
> +```
那为什么你不写 pip install 使用阿里云的镜像源呢。

huggingface 在CN 地区访问慢，是一个常见问题，我们默认onediff的用户遇到后可以自己搜索解决。

你如果一定要写，就整理个 FAQ，把你觉得常见的问题都放进去。

2024-04-18 01:39 UTC, fmk345 commented on ComfyUI_Online_Quantization.md
> +```
done

2024-04-18 03:36 UTC, doombeaker commented on README_ENTERPRISE.md
> +  We provide ComfyUI with an online quantification tool, which has significant acceleration effects. We provide detailed documentation tutorials [ComfyUI online quantitative usage documentation in wi
这里的链接用相对路径。否则预览版里是失效的。

2024-04-18 04:22 UTC, fmk345 commented on README_ENTERPRISE.md
> +  We provide ComfyUI with an online quantification tool, which has significant acceleration effects. We provide detailed documentation tutorials [ComfyUI online quantitative usage documentation in wi
done

2024-04-18 05:36 UTC, doombeaker approved these changes

2024-04-18 05:37 UTC, merged